config/routes.rb
SonglistV11::Application.routes.draw do

  get "/" => 'songlists#index'
  get "/songlists" => 'songlists#index'

end

app/models/songlist.rb
class Songlist < ActiveRecord::Base
  attr_accessible :artist, :category, :label, :sid

  #def categories
  #	categories=self.class.select(:category).group(:category)
  #	r=[]
  #	categories.each do |c|
  #		r<<c.category
  #	end
  #	r
  #end
  #
  #def as_json(options=nil)
  #	h=super
  #	h[:categories]=self.categories
  #	h
  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/songlists_controller.rb
class SonglistsController < ApplicationController
  # GET /songlists
  # GET /songlists.json
  def index
    @songlists = if params[:keyword].to_s!=''
      Songlist.where("label like '%"+params[:keyword]+"%'")
    else
      Songlist
    end

    (@songlists = @songlists.where(:sid=>'0'*(5-params[:sid].to_s.length)+params[:sid].to_s)) if params[:sid].to_s!=''
    (@songlists = @songlists.where(:category=>params[:category])) if params[:category].to_s!=''

    @songlists = @songlists.order(:sid).limit(200)

    categories = Songlist.select(:category).group(:category)
    r = []
    categories.each do |c|
      r << c.category
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: {:data=>@songlists,:categories=>r} }
    end
  end

  # GET /songlists/1
  # GET /songlists/1.json
  def show
    @songlist = Songlist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @songlist }
    end
  end

  # GET /songlists/new
  # GET /songlists/new.json
  def new
    @songlist = Songlist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @songlist }
    end
  end

  # GET /songlists/1/edit
  def edit
    @songlist = Songlist.find(params[:id])
  end

  # POST /songlists
  # POST /songlists.json
  def create
    @songlist = Songlist.new(params[:songlist])

    respond_to do |format|
      if @songlist.save
        format.html { redirect_to @songlist, notice: 'Songlist was successfully created.' }
        format.json { render json: @songlist, status: :created, location: @songlist }
      else
        format.html { render action: "new" }
        format.json { render json: @songlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songlists/1
  # PUT /songlists/1.json
  def update
    @songlist = Songlist.find(params[:id])

    respond_to do |format|
      if @songlist.update_attributes(params[:songlist])
        format.html { redirect_to @songlist, notice: 'Songlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @songlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songlists/1
  # DELETE /songlists/1.json
  def destroy
    @songlist = Songlist.find(params[:id])
    @songlist.destroy

    respond_to do |format|
      format.html { redirect_to songlists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songlists_helper.rb
module SonglistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SonglistV11</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="/ui/style.css">
  <script src="/ui/ui.js"></script>
  </head>
<body>

<%= yield %>

</body>
</html>

app/views/songlists/_form.html.erb
<%= form_for(@songlist) do |f| %>
  <% if @songlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@songlist.errors.count, "error") %> prohibited this songlist from being saved:</h2>

      <ul>
      <% @songlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sid %><br />
    <%= f.text_field :sid %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songlists/edit.html.erb
<h1>Editing songlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @songlist %> |
<%= link_to 'Back', songlists_path %>

app/views/songlists/index.html.erb
<!--

<h1>Listing songlists</h1>

<table>
  <tr>
    <th>Sid</th>
    <th>Category</th>
    <th>Label</th>
    <th>Artist</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @songlists.each do |songlist| %>
  <tr>
    <td><%= songlist.sid %></td>
    <td><%= songlist.category %></td>
    <td><%= songlist.label %></td>
    <td><%= songlist.artist %></td>
    <td><%# link_to 'Show', songlist %></td>
    <td><%# link_to 'Edit', edit_songlist_path(songlist) %></td>
    <td><%# link_to 'Destroy', songlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%# link_to 'New Songlist', new_songlist_path %>

-->

app/views/songlists/new.html.erb
<h1>New songlist</h1>

<%= render 'form' %>

<%= link_to 'Back', songlists_path %>

app/views/songlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sid:</b>
  <%= @songlist.sid %>
</p>

<p>
  <b>Category:</b>
  <%= @songlist.category %>
</p>

<p>
  <b>Label:</b>
  <%= @songlist.label %>
</p>

<p>
  <b>Artist:</b>
  <%= @songlist.artist %>
</p>


<%= link_to 'Edit', edit_songlist_path(@songlist) %> |
<%= link_to 'Back', songlists_path %>